### ISSUE TITLE
Adicoinar erro E203 à lista de ignores do setup.cfg

### ISSUE THREAD

**Issue by daltonmatos** [sixcodes/python-boilerplate#21]
Esse erro acontece pois o black formata essa linha:

```python
 task_id_no_namespace = task_id[task_id.index("_") + 1 :]
```
colocando um espaço entre o `1` e o `:`, mas a regra `E203` diz que esse espaço não deve existir.

Como a formatção final é do black, temos que ignorar essa regra,

**Comment by aguiarcandre** [comment]
Ei Dalton! Posso ficar com essa issue? A ideia é atualizar o setup.cfg adicionando o comentário do erro e o próprio código, correto?

**Comment by daltonmatos** [comment]
Oi @aguiarcandre!

Isso mesmo! Pode abrir o PR sem problemas! Farei a revisão e te ajudo a deixá-lo pronto para mergear.

Obrigado pela ajuda! 🎉🎉

**Comment by aguiarcandre** [comment]
Beleza @daltonmatos, eu que agradeço! Hoje mais tarde abro o PR 😄

**Comment by daltonmatos** [comment]
Tranquilo! Obrigado! 🎉

**Comment by jesuejunior** [comment]
PR foi mergeado, fechando. #22
